sudo: false

language: node_js

node_js:
  - '8'

notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

script:
  - yarn build
  - size
  - yarn examples:build
