version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Check bundle size
          command: yarn size
      - run:
          name: Test packages
          command: yarn test:coverage
      - run:
          name: Build examples
          command: yarn build:examples
